
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: "mirlanuulubakdoolot293/web_course:latest"
    container_name: "web_course"
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/course_project
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      SERVER_PORT: 8080

    depends_on:
      - db
    networks:
      - my-network


  db:
    image: postgres:latest
    container_name: postgres_course
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: course_project
    ports:
      - "6543:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my-network

networks:
  my-network:

volumes:
  postgres_data:
