/*
 * This file is generated by jOOQ.
 */
package hub.bakdoolot.course_project.tables.records;


import hub.bakdoolot.course_project.tables.AccountRating;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AccountRatingRecord extends UpdatableRecordImpl<AccountRatingRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.account_rating.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.account_rating.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.account_rating.id_rating</code>.
     */
    public void setIdRating(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.account_rating.id_rating</code>.
     */
    public Long getIdRating() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.account_rating.id_account</code>.
     */
    public void setIdAccount(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.account_rating.id_account</code>.
     */
    public Long getIdAccount() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AccountRatingRecord
     */
    public AccountRatingRecord() {
        super(AccountRating.ACCOUNT_RATING);
    }

    /**
     * Create a detached, initialised AccountRatingRecord
     */
    public AccountRatingRecord(Long id, Long idRating, Long idAccount) {
        super(AccountRating.ACCOUNT_RATING);

        setId(id);
        setIdRating(idRating);
        setIdAccount(idAccount);
        resetChangedOnNotNull();
    }
}
