/*
 * This file is generated by jOOQ.
 */
package hub.bakdoolot.course_project.tables.records;


import hub.bakdoolot.course_project.tables.AccountCourse;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AccountCourseRecord extends UpdatableRecordImpl<AccountCourseRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.account_course.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.account_course.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.account_course.id_account</code>.
     */
    public void setIdAccount(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.account_course.id_account</code>.
     */
    public Long getIdAccount() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.account_course.id_course</code>.
     */
    public void setIdCourse(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.account_course.id_course</code>.
     */
    public Long getIdCourse() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AccountCourseRecord
     */
    public AccountCourseRecord() {
        super(AccountCourse.ACCOUNT_COURSE);
    }

    /**
     * Create a detached, initialised AccountCourseRecord
     */
    public AccountCourseRecord(Long id, Long idAccount, Long idCourse) {
        super(AccountCourse.ACCOUNT_COURSE);

        setId(id);
        setIdAccount(idAccount);
        setIdCourse(idCourse);
        resetChangedOnNotNull();
    }
}
