/*
 * This file is generated by jOOQ.
 */
package hub.bakdoolot.course_project.tables.records;


import hub.bakdoolot.course_project.tables.Likes;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LikesRecord extends UpdatableRecordImpl<LikesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.likes.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.likes.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.likes.id_account</code>.
     */
    public void setIdAccount(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.likes.id_account</code>.
     */
    public Long getIdAccount() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.likes.id_video</code>.
     */
    public void setIdVideo(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.likes.id_video</code>.
     */
    public Long getIdVideo() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LikesRecord
     */
    public LikesRecord() {
        super(Likes.LIKES);
    }

    /**
     * Create a detached, initialised LikesRecord
     */
    public LikesRecord(Long id, Long idAccount, Long idVideo) {
        super(Likes.LIKES);

        setId(id);
        setIdAccount(idAccount);
        setIdVideo(idVideo);
        resetChangedOnNotNull();
    }
}
