/*
 * This file is generated by jOOQ.
 */
package hub.bakdoolot.course_project.tables.records;


import hub.bakdoolot.course_project.tables.Playlist;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PlaylistRecord extends UpdatableRecordImpl<PlaylistRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.playlist.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.playlist.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.playlist.id_account</code>.
     */
    public void setIdAccount(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.playlist.id_account</code>.
     */
    public Long getIdAccount() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.playlist.id_account_course</code>.
     */
    public void setIdAccountCourse(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.playlist.id_account_course</code>.
     */
    public Long getIdAccountCourse() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PlaylistRecord
     */
    public PlaylistRecord() {
        super(Playlist.PLAYLIST);
    }

    /**
     * Create a detached, initialised PlaylistRecord
     */
    public PlaylistRecord(Long id, Long idAccount, Long idAccountCourse) {
        super(Playlist.PLAYLIST);

        setId(id);
        setIdAccount(idAccount);
        setIdAccountCourse(idAccountCourse);
        resetChangedOnNotNull();
    }
}
