/*
 * This file is generated by jOOQ.
 */
package hub.bakdoolot.course_project.tables.records;


import hub.bakdoolot.course_project.tables.Video;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VideoRecord extends UpdatableRecordImpl<VideoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.video.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.video.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.video.category</code>.
     */
    public void setCategory(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.video.category</code>.
     */
    public String getCategory() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.video.sum_of_likes</code>.
     */
    public void setSumOfLikes(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.video.sum_of_likes</code>.
     */
    public Long getSumOfLikes() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.video.url</code>.
     */
    public void setUrl(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.video.url</code>.
     */
    public String getUrl() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.video.views</code>.
     */
    public void setViews(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.video.views</code>.
     */
    public Long getViews() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.video.id_account</code>.
     */
    public void setIdAccount(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.video.id_account</code>.
     */
    public Long getIdAccount() {
        return (Long) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VideoRecord
     */
    public VideoRecord() {
        super(Video.VIDEO);
    }

    /**
     * Create a detached, initialised VideoRecord
     */
    public VideoRecord(Long id, String category, Long sumOfLikes, String url, Long views, Long idAccount) {
        super(Video.VIDEO);

        setId(id);
        setCategory(category);
        setSumOfLikes(sumOfLikes);
        setUrl(url);
        setViews(views);
        setIdAccount(idAccount);
        resetChangedOnNotNull();
    }
}
