/*
 * This file is generated by jOOQ.
 */
package hub.bakdoolot.course_project.tables;


import hub.bakdoolot.course_project.Keys;
import hub.bakdoolot.course_project.Public;
import hub.bakdoolot.course_project.tables.Course.CoursePath;
import hub.bakdoolot.course_project.tables.Playlist.PlaylistPath;
import hub.bakdoolot.course_project.tables.UserAccount.UserAccountPath;
import hub.bakdoolot.course_project.tables.records.AccountCourseRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AccountCourse extends TableImpl<AccountCourseRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.account_course</code>
     */
    public static final AccountCourse ACCOUNT_COURSE = new AccountCourse();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AccountCourseRecord> getRecordType() {
        return AccountCourseRecord.class;
    }

    /**
     * The column <code>public.account_course.id</code>.
     */
    public final TableField<AccountCourseRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.account_course.id_account</code>.
     */
    public final TableField<AccountCourseRecord, Long> ID_ACCOUNT = createField(DSL.name("id_account"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.account_course.id_course</code>.
     */
    public final TableField<AccountCourseRecord, Long> ID_COURSE = createField(DSL.name("id_course"), SQLDataType.BIGINT, this, "");

    private AccountCourse(Name alias, Table<AccountCourseRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AccountCourse(Name alias, Table<AccountCourseRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.account_course</code> table reference
     */
    public AccountCourse(String alias) {
        this(DSL.name(alias), ACCOUNT_COURSE);
    }

    /**
     * Create an aliased <code>public.account_course</code> table reference
     */
    public AccountCourse(Name alias) {
        this(alias, ACCOUNT_COURSE);
    }

    /**
     * Create a <code>public.account_course</code> table reference
     */
    public AccountCourse() {
        this(DSL.name("account_course"), null);
    }

    public <O extends Record> AccountCourse(Table<O> path, ForeignKey<O, AccountCourseRecord> childPath, InverseForeignKey<O, AccountCourseRecord> parentPath) {
        super(path, childPath, parentPath, ACCOUNT_COURSE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class AccountCoursePath extends AccountCourse implements Path<AccountCourseRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AccountCoursePath(Table<O> path, ForeignKey<O, AccountCourseRecord> childPath, InverseForeignKey<O, AccountCourseRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private AccountCoursePath(Name alias, Table<AccountCourseRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public AccountCoursePath as(String alias) {
            return new AccountCoursePath(DSL.name(alias), this);
        }

        @Override
        public AccountCoursePath as(Name alias) {
            return new AccountCoursePath(alias, this);
        }

        @Override
        public AccountCoursePath as(Table<?> alias) {
            return new AccountCoursePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<AccountCourseRecord> getPrimaryKey() {
        return Keys.ACCOUNT_COURSE_PKEY;
    }

    @Override
    public List<ForeignKey<AccountCourseRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ACCOUNT_COURSE__FK55HUILPTN1UXKV6MS5LUMH21T, Keys.ACCOUNT_COURSE__FKPL8YJ0DPGFX6Q27QAEQNP2LP3);
    }

    private transient UserAccountPath _userAccount;

    /**
     * Get the implicit join path to the <code>public.user_account</code> table.
     */
    public UserAccountPath userAccount() {
        if (_userAccount == null)
            _userAccount = new UserAccountPath(this, Keys.ACCOUNT_COURSE__FK55HUILPTN1UXKV6MS5LUMH21T, null);

        return _userAccount;
    }

    private transient CoursePath _course;

    /**
     * Get the implicit join path to the <code>public.course</code> table.
     */
    public CoursePath course() {
        if (_course == null)
            _course = new CoursePath(this, Keys.ACCOUNT_COURSE__FKPL8YJ0DPGFX6Q27QAEQNP2LP3, null);

        return _course;
    }

    private transient PlaylistPath _playlist;

    /**
     * Get the implicit to-many join path to the <code>public.playlist</code>
     * table
     */
    public PlaylistPath playlist() {
        if (_playlist == null)
            _playlist = new PlaylistPath(this, null, Keys.PLAYLIST__FKOFEGJWRUBYFN8VODKWVX1SN2D.getInverseKey());

        return _playlist;
    }

    @Override
    public AccountCourse as(String alias) {
        return new AccountCourse(DSL.name(alias), this);
    }

    @Override
    public AccountCourse as(Name alias) {
        return new AccountCourse(alias, this);
    }

    @Override
    public AccountCourse as(Table<?> alias) {
        return new AccountCourse(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AccountCourse rename(String name) {
        return new AccountCourse(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AccountCourse rename(Name name) {
        return new AccountCourse(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AccountCourse rename(Table<?> name) {
        return new AccountCourse(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AccountCourse where(Condition condition) {
        return new AccountCourse(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AccountCourse where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AccountCourse where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AccountCourse where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AccountCourse where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AccountCourse where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AccountCourse where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AccountCourse where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AccountCourse whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AccountCourse whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
