/*
 * This file is generated by jOOQ.
 */
package hub.bakdoolot.course_project;


import hub.bakdoolot.course_project.tables.AccountCourse;
import hub.bakdoolot.course_project.tables.AccountRating;
import hub.bakdoolot.course_project.tables.Course;
import hub.bakdoolot.course_project.tables.Likes;
import hub.bakdoolot.course_project.tables.Playlist;
import hub.bakdoolot.course_project.tables.Rating;
import hub.bakdoolot.course_project.tables.TbLike;
import hub.bakdoolot.course_project.tables.UserAccount;
import hub.bakdoolot.course_project.tables.Users;
import hub.bakdoolot.course_project.tables.Video;
import hub.bakdoolot.course_project.tables.records.AccountCourseRecord;
import hub.bakdoolot.course_project.tables.records.AccountRatingRecord;
import hub.bakdoolot.course_project.tables.records.CourseRecord;
import hub.bakdoolot.course_project.tables.records.LikesRecord;
import hub.bakdoolot.course_project.tables.records.PlaylistRecord;
import hub.bakdoolot.course_project.tables.records.RatingRecord;
import hub.bakdoolot.course_project.tables.records.TbLikeRecord;
import hub.bakdoolot.course_project.tables.records.UserAccountRecord;
import hub.bakdoolot.course_project.tables.records.UsersRecord;
import hub.bakdoolot.course_project.tables.records.VideoRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AccountCourseRecord> ACCOUNT_COURSE_PKEY = Internal.createUniqueKey(AccountCourse.ACCOUNT_COURSE, DSL.name("account_course_pkey"), new TableField[] { AccountCourse.ACCOUNT_COURSE.ID }, true);
    public static final UniqueKey<AccountRatingRecord> ACCOUNT_RATING_PKEY = Internal.createUniqueKey(AccountRating.ACCOUNT_RATING, DSL.name("account_rating_pkey"), new TableField[] { AccountRating.ACCOUNT_RATING.ID }, true);
    public static final UniqueKey<CourseRecord> COURSE_PKEY = Internal.createUniqueKey(Course.COURSE, DSL.name("course_pkey"), new TableField[] { Course.COURSE.ID }, true);
    public static final UniqueKey<LikesRecord> LIKES_PKEY = Internal.createUniqueKey(Likes.LIKES, DSL.name("likes_pkey"), new TableField[] { Likes.LIKES.ID }, true);
    public static final UniqueKey<PlaylistRecord> PLAYLIST_PKEY = Internal.createUniqueKey(Playlist.PLAYLIST, DSL.name("playlist_pkey"), new TableField[] { Playlist.PLAYLIST.ID }, true);
    public static final UniqueKey<RatingRecord> RATING_PKEY = Internal.createUniqueKey(Rating.RATING, DSL.name("rating_pkey"), new TableField[] { Rating.RATING.ID }, true);
    public static final UniqueKey<TbLikeRecord> TB_LIKE_PKEY = Internal.createUniqueKey(TbLike.TB_LIKE, DSL.name("tb_like_pkey"), new TableField[] { TbLike.TB_LIKE.ID }, true);
    public static final UniqueKey<UserAccountRecord> USER_ACCOUNT_PKEY = Internal.createUniqueKey(UserAccount.USER_ACCOUNT, DSL.name("user_account_pkey"), new TableField[] { UserAccount.USER_ACCOUNT.ID }, true);
    public static final UniqueKey<UsersRecord> UKHDSJM6L3LUDH1INV75NOEDBPM = Internal.createUniqueKey(Users.USERS, DSL.name("ukhdsjm6l3ludh1inv75noedbpm"), new TableField[] { Users.USERS.ID_ACCOUNT }, true);
    public static final UniqueKey<UsersRecord> USERS_PKEY = Internal.createUniqueKey(Users.USERS, DSL.name("users_pkey"), new TableField[] { Users.USERS.ID }, true);
    public static final UniqueKey<VideoRecord> VIDEO_PKEY = Internal.createUniqueKey(Video.VIDEO, DSL.name("video_pkey"), new TableField[] { Video.VIDEO.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<AccountCourseRecord, UserAccountRecord> ACCOUNT_COURSE__FK55HUILPTN1UXKV6MS5LUMH21T = Internal.createForeignKey(AccountCourse.ACCOUNT_COURSE, DSL.name("fk55huilptn1uxkv6ms5lumh21t"), new TableField[] { AccountCourse.ACCOUNT_COURSE.ID_ACCOUNT }, Keys.USER_ACCOUNT_PKEY, new TableField[] { UserAccount.USER_ACCOUNT.ID }, true);
    public static final ForeignKey<AccountCourseRecord, CourseRecord> ACCOUNT_COURSE__FKPL8YJ0DPGFX6Q27QAEQNP2LP3 = Internal.createForeignKey(AccountCourse.ACCOUNT_COURSE, DSL.name("fkpl8yj0dpgfx6q27qaeqnp2lp3"), new TableField[] { AccountCourse.ACCOUNT_COURSE.ID_COURSE }, Keys.COURSE_PKEY, new TableField[] { Course.COURSE.ID }, true);
    public static final ForeignKey<AccountRatingRecord, RatingRecord> ACCOUNT_RATING__FKQ9IUIOQ3FRQTVCU4K7YBT0W1O = Internal.createForeignKey(AccountRating.ACCOUNT_RATING, DSL.name("fkq9iuioq3frqtvcu4k7ybt0w1o"), new TableField[] { AccountRating.ACCOUNT_RATING.ID_RATING }, Keys.RATING_PKEY, new TableField[] { Rating.RATING.ID }, true);
    public static final ForeignKey<AccountRatingRecord, UserAccountRecord> ACCOUNT_RATING__FKT9SOKTKNM51CEPP6H0K0ON12O = Internal.createForeignKey(AccountRating.ACCOUNT_RATING, DSL.name("fkt9soktknm51cepp6h0k0on12o"), new TableField[] { AccountRating.ACCOUNT_RATING.ID_ACCOUNT }, Keys.USER_ACCOUNT_PKEY, new TableField[] { UserAccount.USER_ACCOUNT.ID }, true);
    public static final ForeignKey<PlaylistRecord, UserAccountRecord> PLAYLIST__FKLAD3BXY6MLCF07CQRN8L4EO24 = Internal.createForeignKey(Playlist.PLAYLIST, DSL.name("fklad3bxy6mlcf07cqrn8l4eo24"), new TableField[] { Playlist.PLAYLIST.ID_ACCOUNT }, Keys.USER_ACCOUNT_PKEY, new TableField[] { UserAccount.USER_ACCOUNT.ID }, true);
    public static final ForeignKey<PlaylistRecord, AccountCourseRecord> PLAYLIST__FKOFEGJWRUBYFN8VODKWVX1SN2D = Internal.createForeignKey(Playlist.PLAYLIST, DSL.name("fkofegjwrubyfn8vodkwvx1sn2d"), new TableField[] { Playlist.PLAYLIST.ID_ACCOUNT_COURSE }, Keys.ACCOUNT_COURSE_PKEY, new TableField[] { AccountCourse.ACCOUNT_COURSE.ID }, true);
    public static final ForeignKey<TbLikeRecord, UserAccountRecord> TB_LIKE__FKJCVCCSKTM0B5AEUWIR1G01XPH = Internal.createForeignKey(TbLike.TB_LIKE, DSL.name("fkjcvccsktm0b5aeuwir1g01xph"), new TableField[] { TbLike.TB_LIKE.ID_ACCOUNT }, Keys.USER_ACCOUNT_PKEY, new TableField[] { UserAccount.USER_ACCOUNT.ID }, true);
    public static final ForeignKey<TbLikeRecord, VideoRecord> TB_LIKE__FKT3W1U0JTEU6PIV1Y1CTPQR8VW = Internal.createForeignKey(TbLike.TB_LIKE, DSL.name("fkt3w1u0jteu6piv1y1ctpqr8vw"), new TableField[] { TbLike.TB_LIKE.ID_VIDEO }, Keys.VIDEO_PKEY, new TableField[] { Video.VIDEO.ID }, true);
    public static final ForeignKey<UsersRecord, UserAccountRecord> USERS__FKJUFG4PSSCKH87O76NF7Y52GRA = Internal.createForeignKey(Users.USERS, DSL.name("fkjufg4pssckh87o76nf7y52gra"), new TableField[] { Users.USERS.ID_ACCOUNT }, Keys.USER_ACCOUNT_PKEY, new TableField[] { UserAccount.USER_ACCOUNT.ID }, true);
    public static final ForeignKey<VideoRecord, UserAccountRecord> VIDEO__FKPOK81KP9SJ5A1O8P714N8NP8Y = Internal.createForeignKey(Video.VIDEO, DSL.name("fkpok81kp9sj5a1o8p714n8np8y"), new TableField[] { Video.VIDEO.ID_ACCOUNT }, Keys.USER_ACCOUNT_PKEY, new TableField[] { UserAccount.USER_ACCOUNT.ID }, true);
}
