/*
 * This file is generated by jOOQ.
 */
package hub.bakdoolot.course_project;


import hub.bakdoolot.course_project.tables.AccountCourse;
import hub.bakdoolot.course_project.tables.AccountRating;
import hub.bakdoolot.course_project.tables.Course;
import hub.bakdoolot.course_project.tables.Likes;
import hub.bakdoolot.course_project.tables.Playlist;
import hub.bakdoolot.course_project.tables.Rating;
import hub.bakdoolot.course_project.tables.TbLike;
import hub.bakdoolot.course_project.tables.UserAccount;
import hub.bakdoolot.course_project.tables.Users;
import hub.bakdoolot.course_project.tables.Video;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.account_course</code>.
     */
    public final AccountCourse ACCOUNT_COURSE = AccountCourse.ACCOUNT_COURSE;

    /**
     * The table <code>public.account_rating</code>.
     */
    public final AccountRating ACCOUNT_RATING = AccountRating.ACCOUNT_RATING;

    /**
     * The table <code>public.course</code>.
     */
    public final Course COURSE = Course.COURSE;

    /**
     * The table <code>public.likes</code>.
     */
    public final Likes LIKES = Likes.LIKES;

    /**
     * The table <code>public.playlist</code>.
     */
    public final Playlist PLAYLIST = Playlist.PLAYLIST;

    /**
     * The table <code>public.rating</code>.
     */
    public final Rating RATING = Rating.RATING;

    /**
     * The table <code>public.tb_like</code>.
     */
    public final TbLike TB_LIKE = TbLike.TB_LIKE;

    /**
     * The table <code>public.user_account</code>.
     */
    public final UserAccount USER_ACCOUNT = UserAccount.USER_ACCOUNT;

    /**
     * The table <code>public.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * The table <code>public.video</code>.
     */
    public final Video VIDEO = Video.VIDEO;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.asList(
            Sequences.ACCOUNT_COURSE_SEQ,
            Sequences.ACCOUNT_RATING_SEQ,
            Sequences.COURSE_SEQ,
            Sequences.LIKE_SEQ,
            Sequences.LIKES_SEQ,
            Sequences.PLAYLIST_SEQ,
            Sequences.RATING_SEQ,
            Sequences.TB_LIKE_SEQ,
            Sequences.USER_ACCOUNT_SEQ,
            Sequences.USERS_SEQ,
            Sequences.VIDEO_SEQ
        );
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            AccountCourse.ACCOUNT_COURSE,
            AccountRating.ACCOUNT_RATING,
            Course.COURSE,
            Likes.LIKES,
            Playlist.PLAYLIST,
            Rating.RATING,
            TbLike.TB_LIKE,
            UserAccount.USER_ACCOUNT,
            Users.USERS,
            Video.VIDEO
        );
    }
}
