/*
 * This file is generated by jOOQ.
 */
package hub.bakdoolot.course_project;


import hub.bakdoolot.course_project.tables.AccountCourse;
import hub.bakdoolot.course_project.tables.AccountRating;
import hub.bakdoolot.course_project.tables.Course;
import hub.bakdoolot.course_project.tables.Likes;
import hub.bakdoolot.course_project.tables.Playlist;
import hub.bakdoolot.course_project.tables.Rating;
import hub.bakdoolot.course_project.tables.TbLike;
import hub.bakdoolot.course_project.tables.UserAccount;
import hub.bakdoolot.course_project.tables.Users;
import hub.bakdoolot.course_project.tables.Video;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.account_course</code>.
     */
    public static final AccountCourse ACCOUNT_COURSE = AccountCourse.ACCOUNT_COURSE;

    /**
     * The table <code>public.account_rating</code>.
     */
    public static final AccountRating ACCOUNT_RATING = AccountRating.ACCOUNT_RATING;

    /**
     * The table <code>public.course</code>.
     */
    public static final Course COURSE = Course.COURSE;

    /**
     * The table <code>public.likes</code>.
     */
    public static final Likes LIKES = Likes.LIKES;

    /**
     * The table <code>public.playlist</code>.
     */
    public static final Playlist PLAYLIST = Playlist.PLAYLIST;

    /**
     * The table <code>public.rating</code>.
     */
    public static final Rating RATING = Rating.RATING;

    /**
     * The table <code>public.tb_like</code>.
     */
    public static final TbLike TB_LIKE = TbLike.TB_LIKE;

    /**
     * The table <code>public.user_account</code>.
     */
    public static final UserAccount USER_ACCOUNT = UserAccount.USER_ACCOUNT;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;

    /**
     * The table <code>public.video</code>.
     */
    public static final Video VIDEO = Video.VIDEO;
}
